### ISSUE TITLE
Env problem with mmcv 

### ISSUE THREAD

**Issue by stanny880913** [pangsu0613/TransCAR#2]
I install mmcv but will get ` ImportError: cannot import name 'DictAction' from 'mmcv'(/home/stannyho/anaconda3/envs/transcar/lib/python3.8/site-packages/mmcv/__init__.py)`, I search google someone said need to install mmcv-full, but when I install mmcv-full 1.4 (I saw your conde env list), it's will show` AssertionError: MMCV==1.4.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.` error, 
How to fix it! 
thank you~

**Comment by MrGoldminer** [comment]
when i change to mmcv>=2.0.0rc4, <2.2.0.,it also have the error:ImportError: cannot import name 'track_iter_progress' from 'mmcv' (/home/goldminer/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/init.py)
